[project]
name = "bearer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "asttokens>=3.0.0",
    "numpy>=2.3.1",
    "torch>=2.7.1",
    "transformers>=4.30.0",
]
